server:
  port: 8002
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: 0.0.0.0
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/