server:
  address: 0.0.0.0
  port: 7002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/

spring:
  application:
    name: service-consumer-application
  redis:
    host: 127.0.0.1
    port: 1234
    # 密码 没有则不填
    password: 123456
    # 连接超时时间
    timeout: 10000s
    #lettuce配置
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10ms